# Generated by Django 5.2.8 on 2026-01-31 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VEGE', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recepie',
            new_name='Receipe',
        ),
        migrations.RenameField(
            model_name='receipe',
            old_name='recepie_description',
            new_name='receipe_description',
        ),
        migrations.RenameField(
            model_name='receipe',
            old_name='recepie_image',
            new_name='receipe_image',
        ),
        migrations.RenameField(
            model_name='receipe',
            old_name='recepie_name',
            new_name='receipe_name',
        ),
    ]
