# Generated by Django 5.2.8 on 2026-03-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VEGE', '0003_receipe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='receipe_view_count',
            field=models.IntegerField(default=1),
        ),
    ]
