# Generated by Django 5.2.8 on 2026-03-04 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VEGE', '0005_department_studentid_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['department']},
        ),
    ]
