# Generated by Django 6.0.3 on 2026-03-21 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VEGE', '0007_subject_studentmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmarks',
            name='marks',
            field=models.IntegerField(default=0),
        ),
    ]
